### ISSUE TITLE
Improve num_qbits_needed

### ISSUE THREAD

**Issue by mwbryant** [mwbryant/quantum-ducks#1]
Change from eq. 15 to eq. 22 in the source paper.  This will add support to more than 2 state nodes.

**Comment by madhunt** [comment]
Eq 22 does not appear to give the correct number for the lesser whistling model (for instance) -- equation might be wrong??

**Comment by mwbryant** [comment]
Should the equation have -2 within the max function?  That is consistent with the existing code and my understanding
