### ISSUE TITLE
Allow more than 2 states

### ISSUE THREAD

**Issue by mwbryant** [mwbryant/quantum-ducks#3]

**Comment by mbruff** [comment]
this issue was vague and I'm not sure if it included generalizing get_probabilities, or just the conditional ones
anyway, I generalized get_probabilities to allow n states as explained in the corresponding code comments and I'll work on conditionals tomorrow

**Comment by mbruff** [comment]
get_probabilities is now generalized to more than 2 parents each with more than 2 states! outputs as nice dictionary. still need to get the graph generalized, unless we work around that with my dict output mentioned above
